package de.montagezeit.app.diagnostics

object DiagnosticWarningCodes {
    const val EMPTY_CONFIRMED_WORK_DAY = "EMPTY_CONFIRMED_WORK_DAY"
    const val MEAL_ALLOWANCE_INELIGIBLE_VALUE_PRESENT = "MEAL_ALLOWANCE_INELIGIBLE_VALUE_PRESENT"
    const val MEAL_ALLOWANCE_RULE_PATH_MISMATCH = "MEAL_ALLOWANCE_RULE_PATH_MISMATCH"
    const val WORK_DURATION_OVERNIGHT_NORMALIZED = "WORK_DURATION_OVERNIGHT_NORMALIZED"
    const val TRAVEL_DURATION_OVERNIGHT_NORMALIZED = "TRAVEL_DURATION_OVERNIGHT_NORMALIZED"
    const val BREAK_EXCEEDS_DURATION = "BREAK_EXCEEDS_DURATION"
    const val TRAVEL_LEG_TOO_LONG = "TRAVEL_LEG_TOO_LONG"
    const val OFF_DAY_HAS_WORK_BLOCK = "OFF_DAY_HAS_WORK_BLOCK"
    const val COMP_TIME_HAS_TRAVEL = "COMP_TIME_HAS_TRAVEL"
    const val UNCONFIRMED_DAY_EXCLUDED = "UNCONFIRMED_DAY_EXCLUDED"
    const val REMINDER_SUPPRESSED_AUTO_OFF = "REMINDER_SUPPRESSED_AUTO_OFF"
    const val REMINDER_SUPPRESSED_ALREADY_FLAGGED = "REMINDER_SUPPRESSED_ALREADY_FLAGGED"
    const val REMINDER_DATE_REJECTED = "REMINDER_DATE_REJECTED"
    const val EXPORT_SKIPPED_EMPTY_RANGE = "EXPORT_SKIPPED_EMPTY_RANGE"
}
